/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ScanSuccessRouteImport } from './routes/scan-success'
import { Route as ScanErrorRouteImport } from './routes/scan-error'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as MealPlanRouteImport } from './routes/meal-plan'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as ExpiringRouteImport } from './routes/expiring'
import { Route as EmptyPantryRouteImport } from './routes/empty-pantry'
import { Route as EmptyFridgeRouteImport } from './routes/empty-fridge'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanSuccessRoute = ScanSuccessRouteImport.update({
  id: '/scan-success',
  path: '/scan-success',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanErrorRoute = ScanErrorRouteImport.update({
  id: '/scan-error',
  path: '/scan-error',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const MealPlanRoute = MealPlanRouteImport.update({
  id: '/meal-plan',
  path: '/meal-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpiringRoute = ExpiringRouteImport.update({
  id: '/expiring',
  path: '/expiring',
  getParentRoute: () => rootRouteImport,
} as any)
const EmptyPantryRoute = EmptyPantryRouteImport.update({
  id: '/empty-pantry',
  path: '/empty-pantry',
  getParentRoute: () => rootRouteImport,
} as any)
const EmptyFridgeRoute = EmptyFridgeRouteImport.update({
  id: '/empty-fridge',
  path: '/empty-fridge',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/empty-fridge': typeof EmptyFridgeRoute
  '/empty-pantry': typeof EmptyPantryRoute
  '/expiring': typeof ExpiringRoute
  '/goals': typeof GoalsRoute
  '/meal-plan': typeof MealPlanRoute
  '/nutrition': typeof NutritionRoute
  '/onboarding': typeof OnboardingRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRoute
  '/recipes': typeof RecipesRoute
  '/scan': typeof ScanRoute
  '/scan-error': typeof ScanErrorRoute
  '/scan-success': typeof ScanSuccessRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/empty-fridge': typeof EmptyFridgeRoute
  '/empty-pantry': typeof EmptyPantryRoute
  '/expiring': typeof ExpiringRoute
  '/goals': typeof GoalsRoute
  '/meal-plan': typeof MealPlanRoute
  '/nutrition': typeof NutritionRoute
  '/onboarding': typeof OnboardingRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRoute
  '/recipes': typeof RecipesRoute
  '/scan': typeof ScanRoute
  '/scan-error': typeof ScanErrorRoute
  '/scan-success': typeof ScanSuccessRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/empty-fridge': typeof EmptyFridgeRoute
  '/empty-pantry': typeof EmptyPantryRoute
  '/expiring': typeof ExpiringRoute
  '/goals': typeof GoalsRoute
  '/meal-plan': typeof MealPlanRoute
  '/nutrition': typeof NutritionRoute
  '/onboarding': typeof OnboardingRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRoute
  '/recipes': typeof RecipesRoute
  '/scan': typeof ScanRoute
  '/scan-error': typeof ScanErrorRoute
  '/scan-success': typeof ScanSuccessRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/empty-fridge'
    | '/empty-pantry'
    | '/expiring'
    | '/goals'
    | '/meal-plan'
    | '/nutrition'
    | '/onboarding'
    | '/planner'
    | '/profile'
    | '/recipes'
    | '/scan'
    | '/scan-error'
    | '/scan-success'
    | '/sitemap.xml'
    | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/empty-fridge'
    | '/empty-pantry'
    | '/expiring'
    | '/goals'
    | '/meal-plan'
    | '/nutrition'
    | '/onboarding'
    | '/planner'
    | '/profile'
    | '/recipes'
    | '/scan'
    | '/scan-error'
    | '/scan-success'
    | '/sitemap.xml'
    | '/product/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/empty-fridge'
    | '/empty-pantry'
    | '/expiring'
    | '/goals'
    | '/meal-plan'
    | '/nutrition'
    | '/onboarding'
    | '/planner'
    | '/profile'
    | '/recipes'
    | '/scan'
    | '/scan-error'
    | '/scan-success'
    | '/sitemap.xml'
    | '/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  EmptyFridgeRoute: typeof EmptyFridgeRoute
  EmptyPantryRoute: typeof EmptyPantryRoute
  ExpiringRoute: typeof ExpiringRoute
  GoalsRoute: typeof GoalsRoute
  MealPlanRoute: typeof MealPlanRoute
  NutritionRoute: typeof NutritionRoute
  OnboardingRoute: typeof OnboardingRoute
  PlannerRoute: typeof PlannerRoute
  ProfileRoute: typeof ProfileRoute
  RecipesRoute: typeof RecipesRoute
  ScanRoute: typeof ScanRoute
  ScanErrorRoute: typeof ScanErrorRoute
  ScanSuccessRoute: typeof ScanSuccessRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan-success': {
      id: '/scan-success'
      path: '/scan-success'
      fullPath: '/scan-success'
      preLoaderRoute: typeof ScanSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan-error': {
      id: '/scan-error'
      path: '/scan-error'
      fullPath: '/scan-error'
      preLoaderRoute: typeof ScanErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal-plan': {
      id: '/meal-plan'
      path: '/meal-plan'
      fullPath: '/meal-plan'
      preLoaderRoute: typeof MealPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expiring': {
      id: '/expiring'
      path: '/expiring'
      fullPath: '/expiring'
      preLoaderRoute: typeof ExpiringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empty-pantry': {
      id: '/empty-pantry'
      path: '/empty-pantry'
      fullPath: '/empty-pantry'
      preLoaderRoute: typeof EmptyPantryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empty-fridge': {
      id: '/empty-fridge'
      path: '/empty-fridge'
      fullPath: '/empty-fridge'
      preLoaderRoute: typeof EmptyFridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  EmptyFridgeRoute: EmptyFridgeRoute,
  EmptyPantryRoute: EmptyPantryRoute,
  ExpiringRoute: ExpiringRoute,
  GoalsRoute: GoalsRoute,
  MealPlanRoute: MealPlanRoute,
  NutritionRoute: NutritionRoute,
  OnboardingRoute: OnboardingRoute,
  PlannerRoute: PlannerRoute,
  ProfileRoute: ProfileRoute,
  RecipesRoute: RecipesRoute,
  ScanRoute: ScanRoute,
  ScanErrorRoute: ScanErrorRoute,
  ScanSuccessRoute: ScanSuccessRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
